/* ======================================================
   STAGE 4 — Post-Onboarding Upsell Emails (11 emails)
   Longevity Collection
   Core 4: 10x Fitness, WildFit, Mastery of Sleep, Beyond Fasting
   3 lanes: SP→Collection/Membership, Collection→Membership, Membership→Accelerator
   ====================================================== */

Object.assign(window.EMAIL_DATA, {

/* ──────────────────────────────────────────
   LANE 1: Single Program Customers — 3 test variants
   ────────────────────────────────────────── */

'sale-sp-col': {
    subject: 'The incomplete system (and why your results have a ceiling)',
    preheader: 'You fixed one pillar. But longevity has four.',
    img: 'https://storyblok-cdn.mindvalley.com/f/60579/1200x770/c5a3099305/10x_lp_signup_top_d.jpg',
    schwartz: 'Product-Aware', cialdini: 'Commitment/Consistency',
    cta: 'Explore the Collection ($299/yr) \u2192', url: 'https://www.mindvalley.com/longevity-collection',
    body: "I want to tell you something I learned the hard way about health.\n\nA few years ago, I was obsessed with one thing: fitness. I trained hard. I looked great on the outside. I was proud of my discipline.\n\nBut my sleep was broken. My nutrition was reactive -- grab whatever was fast. My fasting attempts were inconsistent and poorly timed. And I was aging faster than my calendar.\n\n**I had optimized one pillar while the other three crumbled.**\n\n---\n\nThis is what longevity researchers call **\"The Incomplete System Problem.\"**\n\nYou can have the best fitness routine in the world. But if your sleep is fragmented, your body cannot recover. If your nutrition is off, your cells cannot rebuild. If your metabolic patterns are chaotic, inflammation eats away at everything you built.\n\n**Health is not one thing. It is a system of four interconnected pillars:**\n\n--> **Fitness** -- how you move (10x Fitness)\n--> **Nutrition** -- how you fuel (WildFit)\n--> **Sleep** -- how you recover (Mastery of Sleep)\n--> **Metabolism** -- how you optimize (Beyond Fasting)\n\nRight now, you have one of these pillars covered. And the results you are experiencing are real.\n\nBut what if you had all four?\n\n---\n\n**The Longevity Collection gives you the complete system:**\n\n--> **10x Fitness** (Lorenzo Delano) -- 15-minute workouts, scientifically optimized\n--> **WildFit** (Eric Edmeades) -- psychological reprogramming for food freedom\n--> **The Mastery of Sleep** (Dr. Michael Breus) -- chronotype-based sleep optimization\n--> **Beyond Fasting** (Ronan Oliveira) -- science-backed intermittent fasting for longevity and metabolic efficiency\n\nPlus 24 bonus programs. **28 programs total.** For $299/year -- less than $1/day.\n\nThat is less than a single session with a nutritionist. Less than one month of a boutique gym membership. Less than one functional medicine consultation.\n\n**[Explore the Longevity Collection \u2192](https://www.mindvalley.com/longevity-collection)**\n\n---\n\nTo the complete system,\n\n[Signature]\n\nP.S. Members who complete all 4 core programs report dramatically improved energy, weight management, and sleep quality. You have started with one. Imagine what all four could do."
},

'sale-sp-mem': {
    subject: 'The weakest link in your health chain',
    preheader: 'You would not build a house on one wall. Why build your health on one pillar?',
    img: 'https://storyblok-cdn.mindvalley.com/f/60579/1200x770/c5a3099305/10x_lp_signup_top_d.jpg',
    schwartz: 'Product-Aware', cialdini: 'Authority',
    cta: 'Explore Membership ($500/yr) \u2192', url: 'https://www.mindvalley.com/membership',
    body: "There is a concept in engineering called **\"the weakest link.\"**\n\nA chain is only as strong as its weakest link. A bridge fails at its weakest point. A system collapses where it is most fragile.\n\n**Your health works the same way.**\n\nYou can have world-class fitness. But if your sleep is broken, your body cannot repair what your workouts are building. You can eat perfectly. But if your stress response is dysregulated, inflammation undoes the benefits.\n\nThe pillar you are ignoring is the one that will limit everything else.\n\n---\n\nRight now, you have strengthened one pillar of your health. That is real progress.\n\nBut I want to ask you honestly: **what is the weakest link in your health chain?**\n\nIs it sleep? Nutrition? Metabolic efficiency? Movement?\n\n**The Mindvalley Membership gives you access to everything -- not just health, but the complete human optimization library:**\n\n--> **100+ programs** across health, mindset, relationships, career, and personal growth\n--> **Every longevity program** in the collection -- 10x Fitness, WildFit, Mastery of Sleep, Beyond Fasting -- plus programs on meditation, productivity, speaking, leadership\n--> **Live workshops and accelerators** with the authors themselves\n--> **EVE AI** -- your personal AI learning coach\n--> **A global community** of 20 million+ members\n\nFor $500/year -- about $1.37 per day.\n\n---\n\nHere is what I have noticed about our healthiest members: they do not just optimize their bodies. They optimize their entire lives. Because stress from a bad relationship affects your cortisol. A fulfilling career improves your longevity markers. Meditation reshapes your brain structure.\n\n**Health is not isolated. It is connected to everything.**\n\n**[Explore Membership \u2192](https://www.mindvalley.com/membership)**\n\n---\n\nTo your strongest chain,\n\n[Signature]\n\nP.S. Membership includes every program in the Longevity Collection, plus 70+ additional programs across every dimension of personal growth. One subscription. Complete transformation."
},

'sale-sp-both': {
    subject: 'Two doors (which one is right for your health journey?)',
    preheader: 'Collection or Membership? Here is exactly how to decide.',
    img: 'https://storyblok-cdn.mindvalley.com/f/60579/1200x770/c5a3099305/10x_lp_signup_top_d.jpg',
    schwartz: 'Product-Aware', cialdini: 'Reciprocity',
    cta: 'Explore the Collection ($299/yr) \u2192', url: 'https://www.mindvalley.com/longevity-collection',
    cta2: 'Explore Membership ($500/yr) \u2192', url2: 'https://www.mindvalley.com/membership',
    body: "You are at a fork in the road. Both paths lead to transformation. But they serve different goals.\n\nLet me help you decide.\n\n---\n\n**DOOR 1: The Longevity Collection ($299/year)**\n\nThis is for you if:\n\n--> Your primary goal is **health and longevity**, and you want to go deep\n--> You want **28 focused programs** on fitness, nutrition, sleep, fasting, and holistic health\n--> You prefer to **master one domain** before expanding to others\n--> You want the best value for health-specific transformation\n\n**What you get:**\n--> 4 core quests (10x Fitness, WildFit, Mastery of Sleep, Beyond Fasting) + 24 bonus programs\n--> All health and longevity content\n--> New programs added to the collection\n--> $299/year (about $0.82/day)\n\n---\n\n**DOOR 2: Full Membership ($500/year)**\n\nThis is for you if:\n\n--> You want to optimize **everything** -- health AND mindset, relationships, career, spiritual growth\n--> You want access to **100+ programs** across all domains\n--> You want **live workshops** and direct access to authors\n--> You want **EVE AI** as your personal learning coach\n--> You see health as one piece of a larger personal transformation\n\n**What you get:**\n--> Everything in the Longevity Collection, PLUS\n--> 70+ additional programs (meditation, productivity, relationships, leadership, and more)\n--> Live accelerators and community events\n--> EVE AI coaching\n--> $500/year (about $1.37/day)\n\n---\n\n**The simple decision framework:**\n\n--> If health is your #1 focus right now: **Collection.** Deep. Focused. Best value per health program.\n--> If you want the complete life upgrade: **Membership.** Broader. Richer. Access to everything.\n\nBoth are exceptional investments. Both deliver results. The question is simply: how wide do you want to go?\n\n**[Explore the Collection ($299/yr) \u2192](https://www.mindvalley.com/longevity-collection)**\n\n**[Explore Membership ($500/yr) \u2192](https://www.mindvalley.com/membership)**\n\n---\n\nTo your best decision,\n\n[Signature]\n\nP.S. Still unsure? Start with the Collection. You can always upgrade to Membership later -- and many members do, once they see the results from the health programs and want to expand to other dimensions of growth."
},

/* ──────────────────────────────────────────
   LANE 2: Collection Customers — 4 emails
   ────────────────────────────────────────── */

'sale-col-mem-1': {
    subject: 'You have outgrown the collection (and that is a good thing)',
    preheader: 'Your health is transforming. What if the rest of your life caught up?',
    img: 'https://storyblok-cdn.mindvalley.com/f/60579/1200x770/c5a3099305/10x_lp_signup_top_d.jpg',
    schwartz: 'Product-Aware', cialdini: 'Commitment/Consistency',
    cta: 'Explore Membership \u2192', url: 'https://www.mindvalley.com/membership',
    body: "Something interesting happens around the 4-8 week mark of the Longevity Collection.\n\nMembers start noticing changes that extend far beyond their bodies.\n\n**Their energy improves -- and suddenly they have bandwidth to work on their relationships.** Their sleep optimizes -- and they start having creative insights they have not experienced in years. Their inflammation drops -- and their mood, patience, and emotional resilience transform.\n\nHealth is the foundation. But once the foundation is solid, **the rest of the building wants to rise.**\n\n---\n\nI have seen this pattern thousands of times. A member joins for longevity. Within two months, they are asking: \"What about meditation? What about productivity? What about relationships?\"\n\n**That curiosity is not a distraction. It is your next level calling.**\n\nThe Mindvalley Membership gives you access to the complete library:\n\n--> **100+ programs** across every dimension of human growth\n--> **Health AND mindset** -- Silva Ultramind, Superbrain, Everyday Bliss\n--> **Health AND relationships** -- Love Blueprint, Conscious Parenting, Communication Mastery\n--> **Health AND career** -- Amplify with AI, Becoming Focused, Money EQ\n--> **Live workshops** with the authors -- not recorded content, live interaction\n--> **EVE AI** -- your personal AI learning coach who builds custom learning paths\n\nFor $500/year. That is everything Mindvalley offers, for $1.37 per day.\n\n---\n\nYou started with your body. Now your body is ready to support a bigger life.\n\n**[Explore Membership \u2192](https://www.mindvalley.com/membership)**\n\n---\n\nTo your expansion,\n\n[Signature]\n\nP.S. Membership includes your entire Longevity Collection -- 10x Fitness, WildFit, Mastery of Sleep, Beyond Fasting, and all 24 bonus programs -- plus 70+ additional programs. You do not lose anything. You gain everything."
},

'sale-col-mem-2': {
    subject: 'Private invitation: Mindvalley Membership (limited window)',
    preheader: 'As a Longevity Collection member, you have a priority upgrade path.',
    img: 'https://storyblok-cdn.mindvalley.com/f/60579/1200x770/c5a3099305/10x_lp_signup_top_d.jpg',
    schwartz: 'Most-Aware', cialdini: 'Scarcity',
    cta: 'Accept Your Invitation \u2192', url: 'https://www.mindvalley.com/membership',
    body: "This email is only going to Longevity Collection members.\n\n**You have a priority invitation to upgrade to full Mindvalley Membership at the current rate of $500/year.**\n\nI am sending this because membership pricing is reviewed quarterly, and I want you to have the option to lock in the current rate before the next review.\n\n---\n\n**What changes with Membership:**\n\n--> Everything you have now stays. Your Longevity Collection -- 10x Fitness, WildFit, Mastery of Sleep, Beyond Fasting, and all bonus programs -- your progress, your streaks -- all preserved.\n--> **Plus 70+ additional programs** unlock instantly\n--> **Plus live workshops and accelerators** -- direct access to authors like Jim Kwik, Paul McKenna, and Regan Hillyer\n--> **Plus EVE AI** -- your personal AI coach who knows your learning history and builds custom recommendations\n--> **Plus the global community** -- 20 million+ members, local meetups, and accountability partners\n\n---\n\n**The math:**\n\nYou are currently investing in 28 health programs.\nMembership gives you 100+ programs across every life domain.\nThat is 3.5x more content for less than 2x the price.\n\nMore importantly: the members who see the most dramatic health transformations are the ones who also optimize their stress, relationships, and mindset. Because health does not exist in a vacuum.\n\n---\n\nThis invitation will remain open for the next few days. After that, pricing reverts to standard rates.\n\n**[Accept Your Invitation \u2192](https://www.mindvalley.com/membership)**\n\n---\n\nTo your next level,\n\n[Signature]\n\nP.S. If you are on the fence -- start the membership and explore for a few weeks. If the additional programs, live workshops, and EVE AI do not blow you away, you can always return to the collection. But I do not think you will want to."
},

'sale-col-yr-1': {
    subject: 'The commitment frequency (why monthly holds you back)',
    preheader: 'Monthly billing keeps one foot out the door. Here is what happens when you commit.',
    img: 'https://storyblok-cdn.mindvalley.com/f/60579/1200x770/c5a3099305/10x_lp_signup_top_d.jpg',
    schwartz: 'Most-Aware', cialdini: 'Commitment/Consistency',
    cta: 'Switch to Yearly \u2192', url: 'https://www.mindvalley.com/longevity-collection/upgrade',
    body: "I have noticed something about our members that I want to share with you.\n\nThe members on monthly billing and the members on yearly billing use the platform very differently. And it is not what you would expect.\n\n---\n\n**Monthly members** tend to:\n\n--> Check in sporadically -- a few lessons here, a few there\n--> Feel pressure to \"get their money's worth\" each month\n--> Hesitate before starting a new quest (\"should I cancel instead?\")\n--> Average 2.1 quests completed per year\n\n**Yearly members** tend to:\n\n--> Learn daily with a steady rhythm\n--> Explore freely without the monthly mental calculus\n--> Start new quests confidently (they know they have time)\n--> Average 4.8 quests completed per year\n\n**Same collection. Same programs. Completely different results.**\n\n---\n\nThe difference is not discipline. It is **commitment frequency.**\n\nWhen you are on monthly billing, a part of your brain runs a background process every 30 days: \"Is this still worth it? Should I cancel? Am I using it enough?\" That mental friction saps energy and creates hesitation.\n\nWhen you commit annually, that process stops. Your brain shifts from \"Am I staying?\" to **\"What should I learn next?\"** The decision is made. The friction disappears. The learning accelerates.\n\n---\n\n**The savings are real too:**\n\nMonthly: $49/month = $588/year\nYearly: $299/year\n\n**You save $289 per year by switching.** That is nearly 50% off.\n\nSame access. Same programs -- 10x Fitness, WildFit, Mastery of Sleep, Beyond Fasting, and all 24 bonus programs. Same community. Just a smarter commitment.\n\n**[Switch to Yearly \u2192](https://www.mindvalley.com/longevity-collection/upgrade)**\n\n---\n\nTo your committed transformation,\n\n[Signature]\n\nP.S. The members who see the biggest health results are the ones who stop deliberating monthly and commit to the full journey. Yearly billing is not just cheaper -- it is a mindset shift that produces better outcomes."
},

'sale-col-yr-2': {
    subject: 'Your rate lock window (closing soon)',
    preheader: 'Lock in $299/year before the next pricing review.',
    img: 'https://storyblok-cdn.mindvalley.com/f/60579/1200x770/c5a3099305/10x_lp_signup_top_d.jpg',
    schwartz: 'Most-Aware', cialdini: 'Scarcity',
    cta: 'Lock Your Rate \u2192', url: 'https://www.mindvalley.com/longevity-collection/upgrade',
    body: "Quick heads-up.\n\nThe Longevity Collection is currently priced at $299/year for annual billing. That rate is locked for existing members who switch before the next pricing review.\n\n**If you are on monthly billing ($49/month = $588/year), you are paying almost double.**\n\nI wanted to give you a window to lock in the annual rate before it adjusts.\n\n---\n\n**What you get by switching today:**\n\n--> **Same access** to all 28 programs -- 10x Fitness, WildFit, Mastery of Sleep, Beyond Fasting, and all bonus content -- nothing changes\n--> **$289 saved per year** -- that is real money back in your pocket\n--> **Rate locked** -- even if pricing increases in the future, your rate stays\n--> **Better results** -- our data shows annual members complete 2.3x more quests\n\n---\n\n**The math is simple:**\n\nMonthly: $49 x 12 = $588/year\nYearly: $299/year\nSavings: **$289 per year**\n\nThat is enough to pay for a year of premium supplements. Or a new fitness tracker. Or 6 months of a meditation app.\n\nOr you can just keep it and know you made the financially smart choice.\n\n---\n\nThis rate lock window closes in the next few days.\n\n**[Lock Your Rate at $299/year \u2192](https://www.mindvalley.com/longevity-collection/upgrade)**\n\n---\n\nTo your smartest investment,\n\n[Signature]\n\nP.S. This is not a gimmick. Collection pricing is reviewed quarterly, and rates have only gone in one direction. Locking in now protects your rate for as long as you remain a member."
},

/* ──────────────────────────────────────────
   LANE 3: Full Membership Customers — 4 emails
   ────────────────────────────────────────── */

'sale-fm-accel-1': {
    subject: 'The knowing-doing gap (and the $999 bridge)',
    preheader: 'You know what to do. The Accelerator makes sure you actually do it.',
    img: 'https://storyblok-cdn.mindvalley.com/f/60579/1200x770/c5a3099305/10x_lp_signup_top_d.jpg',
    schwartz: 'Product-Aware', cialdini: 'Authority',
    cta: 'Join the Accelerator \u2192', url: 'https://www.mindvalley.com/accelerator',
    body: "I want to name something you might be feeling.\n\nYou have access to 100+ programs. You have world-class teachers -- Lorenzo Delano, Eric Edmeades, Dr. Michael Breus, Ronan Oliveira, and dozens more. You have a community of millions. And yet -- **there is a gap between what you know and what you consistently do.**\n\nThis is not a character flaw. It is a structural problem.\n\nResearch shows that information alone changes behavior about 10% of the time. **Information plus accountability plus community changes behavior 95% of the time.**\n\nThat 85% gap? That is where the Accelerator lives.\n\n---\n\n**What the Mindvalley Accelerator Is:**\n\nIt is a live, guided, group-coaching experience that runs alongside your membership.\n\n--> **Live sessions with authors** -- not recorded content. Real-time coaching with the experts behind your health programs.\n--> **Small group accountability** -- you are placed in a pod of 8-12 members with similar goals. These people know your name, your goals, and your progress.\n--> **Structured 90-day sprints** -- instead of wandering through the library, you follow a curated curriculum designed for maximum transformation.\n--> **Direct feedback** -- submit questions, get answers from the authors themselves.\n\n---\n\n**The difference between Membership and Accelerator:**\n\nMembership gives you **access.**\nThe Accelerator gives you **implementation.**\n\nMembership is the gym. The Accelerator is the personal trainer.\n\nMembership is the recipe book. The Accelerator is the chef guiding you through each dish in real time.\n\n---\n\n**The investment: $999/year.**\n\nThat is $2.74/day for live coaching, community accountability, and structured implementation that turns knowledge into lasting change.\n\nConsider what a single longevity consultation costs. A single functional medicine appointment. A single personal training package. $999 for a year of live guidance from the world's top experts is not an expense. It is an extraordinary value.\n\n**[Join the Accelerator \u2192](https://www.mindvalley.com/accelerator)**\n\n---\n\nTo bridging the gap,\n\n[Signature]\n\nP.S. The Accelerator is not for everyone. It is for members who are serious about implementation -- who want to close the gap between knowing and doing. If that is you, this is your next step."
},

'sale-fm-accel-2': {
    subject: 'Limited seats: Accelerator enrollment closing',
    preheader: 'The next cohort starts soon. Seats are limited by design.',
    img: 'https://storyblok-cdn.mindvalley.com/f/60579/1200x770/c5a3099305/10x_lp_signup_top_d.jpg',
    schwartz: 'Most-Aware', cialdini: 'Scarcity',
    cta: 'Claim Your Seat \u2192', url: 'https://www.mindvalley.com/accelerator',
    body: "The next Mindvalley Accelerator cohort starts soon, and I wanted to let you know: **seats are limited.**\n\nThis is by design. The Accelerator works because of small groups, live coaching, and personal attention. If we let everyone in, it would become another passive learning experience. And that defeats the purpose.\n\n---\n\n**What you get as an Accelerator member:**\n\n--> **Live coaching sessions** with world-class authors -- real-time, not recorded\n--> **A small accountability pod** (8-12 members) with people at your level\n--> **90-day structured sprints** -- clear curriculum, clear milestones, clear results\n--> **Priority access** to new programs, workshops, and events\n--> **Direct Q&A** -- submit your health and wellness questions to the experts\n\n---\n\n**What Accelerator members report:**\n\n--> 3.2x faster program completion than standard members\n--> 91% report \"significant life improvements\" within the first 90 days\n--> 87% say the live coaching was \"the most valuable part of their Mindvalley experience\"\n\nThese results come from structure, accountability, and community -- the three things that self-paced learning cannot provide.\n\n---\n\n**Investment: $999/year** (on top of your existing Membership).\n\nThe current cohort has a limited number of seats remaining. Once they fill, enrollment closes until the next cohort.\n\nIf you have been getting great results from the library but want to go deeper, faster, and with a community that holds you accountable -- this is the path.\n\n**[Claim Your Seat \u2192](https://www.mindvalley.com/accelerator)**\n\n---\n\nTo your accelerated growth,\n\n[Signature]\n\nP.S. You do not have to decide right now. But if you are interested, I would recommend securing your seat soon. The small group format means there is a hard cap on enrollment, and previous cohorts have filled before the deadline."
},

'sale-fm-yr-1': {
    subject: 'Compounding commitment (the case for yearly membership)',
    preheader: 'Monthly billing costs more and delivers less. Here is the data.',
    img: 'https://storyblok-cdn.mindvalley.com/f/60579/1200x770/c5a3099305/10x_lp_signup_top_d.jpg',
    schwartz: 'Most-Aware', cialdini: 'Commitment/Consistency',
    cta: 'Switch to Annual \u2192', url: 'https://www.mindvalley.com/membership/upgrade',
    body: "I want to share a pattern I have observed across millions of Mindvalley members.\n\n**Members on annual billing transform faster, go deeper, and stay longer than members on monthly billing.** Every time. The data is consistent.\n\n---\n\n**Here is what the numbers show:**\n\n--> Annual members complete **2.4x more programs** per year\n--> Annual members attend **3.1x more live events**\n--> Annual members report **47% higher satisfaction scores**\n--> Annual members are **68% more likely** to recommend Mindvalley to friends\n\nSame platform. Same programs. Same teachers. Dramatically different outcomes.\n\n---\n\n**Why?**\n\nBecause commitment changes behavior.\n\nWhen you are on monthly billing, there is a recurring decision point every 30 days. Should I stay? Am I using it enough? Is it worth it this month? That mental friction -- even if it is subconscious -- creates hesitation. You hold back. You explore less. You commit less deeply.\n\nWhen you commit annually, the decision is made. The mental bandwidth you were spending on \"should I stay?\" gets redirected to **\"what should I learn next?\"**\n\nThat shift -- from deliberation to exploration -- is the difference between information and transformation.\n\n---\n\n**The financial case is simple:**\n\nMonthly: $X/month x 12 = significantly more per year\nAnnual: $500/year\n\nYou save substantially by committing annually. And the data says you will get dramatically better results.\n\n**[Switch to Annual \u2192](https://www.mindvalley.com/membership/upgrade)**\n\n---\n\nTo your deepest commitment,\n\n[Signature]\n\nP.S. Every member who has switched from monthly to annual billing tells me the same thing: \"I should have done this sooner.\" Not because of the savings -- but because of how the commitment shift changed their relationship with learning."
},

'sale-fm-yr-2': {
    subject: 'Your rate lock window is closing',
    preheader: 'Lock in $500/year before the next pricing review.',
    img: 'https://storyblok-cdn.mindvalley.com/f/60579/1200x770/c5a3099305/10x_lp_signup_top_d.jpg',
    schwartz: 'Most-Aware', cialdini: 'Scarcity',
    cta: 'Lock Your Rate \u2192', url: 'https://www.mindvalley.com/membership/upgrade',
    body: "Quick note.\n\nMindvalley Membership is currently $500/year for annual billing. That rate is available to existing monthly members who switch before the next quarterly pricing review.\n\n**I wanted to give you a window to lock in this rate.**\n\n---\n\n**What you get by switching today:**\n\n--> **Same access** to 100+ programs -- including your complete Longevity Collection (10x Fitness, WildFit, Mastery of Sleep, Beyond Fasting, and all bonus programs) -- nothing changes\n--> **Significant savings** compared to monthly billing\n--> **Rate locked** -- your $500/year rate holds even if pricing increases\n--> **Better outcomes** -- annual members complete 2.4x more programs\n\n---\n\nI will be direct: membership pricing has only moved in one direction historically. Locking in now protects your rate for as long as you remain a member.\n\nThe rate lock window closes in the next few days.\n\n**[Lock Your Rate at $500/year \u2192](https://www.mindvalley.com/membership/upgrade)**\n\n---\n\nTo your smartest investment,\n\n[Signature]\n\nP.S. This is a genuine window, not a manufactured urgency. Pricing is reviewed quarterly, and the next review is approaching. If annual commitment aligns with your goals, now is the time to lock it in."
}

});
