/* ======================================================
   STAGE 3 — Collection Customer Onboarding (9 emails / 21 days)
   Longevity Collection · $399 · 28 programs
   Core 4: 10x Fitness, WildFit, The Mastery of Sleep, Beyond Fasting
   ====================================================== */

Object.assign(window.EMAIL_DATA, {

'co-1': {
    subject: "You're in! Welcome to the Longevity Collection",
    preheader: '28 programs. 4 core quests. Your login is inside.',
    img: 'https://storyblok-cdn.mindvalley.com/f/60579/1200x770/c5a3099305/10x_lp_signup_top_d.jpg',
    schwartz: 'Most-Aware', cialdini: 'Commitment',
    cta: 'Log In & Explore \u2192', url: 'https://www.mindvalley.com/longevity-collection',
    body: "Congratulations. You just made a decision that most people will never make.\n\nYou did not buy a course. **You invested in decades -- potentially decades -- of healthy, vibrant, high-performance living that most people leave on the table.**\n\nThe Longevity Collection is now live in your account. Let me walk you through exactly what you have.\n\n---\n\n**What You Now Have Access To:**\n\n--> **28 transformational programs** spanning fitness, nutrition, sleep, fasting, longevity science, and holistic health\n--> **4 flagship Quests** handpicked as your starting foundation\n--> **Hundreds of lessons** -- each designed for 15-20 minutes a day\n--> **New programs and updates** added to the collection over time\n\n---\n\n**Your 4 Core Quests:**\n\n--> **10x Fitness** (Lorenzo Delano) -- build the body you want in just 15 minutes, twice a week\n--> **WildFit** (Eric Edmeades) -- reprogram your relationship with food at the deepest level\n--> **The Mastery of Sleep** (Dr. Michael Breus) -- optimize every sleep cycle for peak recovery and performance\n--> **Beyond Fasting** (Ronan Oliveira) -- master intermittent fasting for metabolic efficiency, longevity, and effortless weight management\n\nPlus 24 bonus programs covering everything from breathwork to stress management to peak physical performance.\n\n---\n\n**Where to Start:**\n\nMost members begin with one of two paths:\n\n--> **10x Fitness** -- if you want visible, physical results fast. 15-minute workouts you can start today.\n--> **WildFit** -- if food is your biggest struggle. Eric Edmeades's psychological approach dissolves cravings without willpower.\n\nBoth take about 15-20 minutes per day. Both deliver results within the first week.\n\nYour collection is waiting. Log in, pick your path, and press play.\n\n**[Log In & Explore \u2192](https://www.mindvalley.com/longevity-collection)**\n\n---\n\nTo your longest, healthiest life,\n\n[Signature]\n\nP.S. Tomorrow, I will show you how to take this entire collection with you everywhere -- in your pocket, on your morning walk, at the gym. The transformation never has to stop."
},

'co-2': {
    subject: 'Download the app (transform anywhere, anytime)',
    preheader: 'Your morning walk, your gym session, your commute -- all become health upgrades.',
    img: 'https://storyblok-cdn.mindvalley.com/f/60579/1200x770/c5a3099305/10x_lp_signup_top_d.jpg',
    schwartz: 'Most-Aware', cialdini: 'Commitment',
    cta: 'Download App \u2192', url: 'https://www.mindvalley.com/app',
    body: "The healthiest people I know have one thing in common: **they turn ordinary moments into transformation time.**\n\nThe morning walk. The gym session. The 15 minutes before bed. The commute.\n\nWith the Mindvalley app, your entire Longevity Collection travels with you.\n\n---\n\n**What the App Gives You:**\n\n--> **Stream or download lessons offline** -- no Wi-Fi needed. Perfect for the gym, the trail, and unplugged mornings.\n--> **Daily micro-lessons (15-20 min)** -- structured so you never have to wonder \"what should I do for my health today?\"\n--> **Progress tracking** -- see your streaks, completed lessons, and milestones at a glance.\n--> **Community access** -- connect with health-focused members from 195 countries who are on the same journey.\n\n---\n\n**How Top Members Use It:**\n\n--> Morning walk + Beyond Fasting lesson = start the day with a metabolic optimization protocol\n--> Gym session + 10x Fitness guidance = train smarter in half the time\n--> Evening wind-down + Mastery of Sleep = optimize tonight's recovery before you close your eyes\n\nThe compound effect of learning during moments you would otherwise waste is staggering. 15 minutes a day becomes 91 hours of focused health education per year.\n\n---\n\n**Download now and your collection will sync automatically.**\n\n--> [iOS App Store](https://apps.apple.com/us/app/mindvalley-self-improvement/id1108786610)\n--> [Google Play Store](https://play.google.com/store/apps/details?id=com.mindvalley.mva)\n\n**[Download App \u2192](https://www.mindvalley.com/app)**\n\n---\n\nTo health in every moment,\n\n[Signature]\n\nP.S. Tomorrow, I will help you decide exactly which quest to start first. A simple framework that takes 60 seconds and points you to the perfect starting point for where your health is right now."
},

'co-3': {
    subject: 'Which quest should you start first? (60-second health audit)',
    preheader: '4 paths. One is perfect for your biggest health bottleneck right now.',
    img: 'https://storyblok-cdn.mindvalley.com/f/60579/1200x770/c5a3099305/10x_lp_signup_top_d.jpg',
    schwartz: 'Product-Aware', cialdini: 'Reciprocity',
    cta: 'Start 10x Fitness \u2192', url: 'https://www.mindvalley.com/longevity-collection',
    body: "You have 28 programs at your fingertips. That is powerful -- but I do not want you staring at a menu when you could be transforming your health.\n\n**So here is a 60-second decision framework.**\n\nAnswer one question: **What is your biggest health bottleneck right now?**\n\n---\n\n**If your biggest issue is FITNESS and ENERGY:**\n\n--> Start with **10x Fitness** (Lorenzo Delano)\n--> You feel sluggish, heavy, or drained by mid-afternoon. Lorenzo's 15-minute micro-workouts are scientifically designed to flood your body with energy, build lean muscle, and boost metabolism -- without spending hours at the gym.\n\n**If FOOD is your struggle:**\n\n--> Start with **WildFit** (Eric Edmeades)\n--> You have tried diets. They work for a while, then they do not. Eric's approach is different -- it rewires your psychology around food so cravings dissolve naturally. No willpower required. No calorie counting. Just a new relationship with what you eat.\n\n**If SLEEP is broken:**\n\n--> Start with **The Mastery of Sleep** (Dr. Michael Breus)\n--> You wake up tired, toss and turn, or rely on caffeine to function. Dr. Breus -- \"The Sleep Doctor\" -- has appeared on Dr. Oz over 40 times. His chronotype system matches your sleep schedule to your biology. Most members report better sleep within the first week.\n\n**If you want METABOLIC OPTIMIZATION:**\n\n--> Start with **Beyond Fasting** (Ronan Oliveira)\n--> You want to unlock the science of intermittent fasting -- for weight loss, longevity, mental clarity, and workout amplification. Ronan has facilitated over 300,000 body transformations. His approach addresses the when, what, how, and why of eating.\n\n---\n\n**Not sure? Start with 10x Fitness.**\n\nIt gives you the fastest visible results and builds momentum for everything that follows. Most members find it energizing enough to propel them into their second quest.\n\n**[Start 10x Fitness \u2192](https://www.mindvalley.com/longevity-collection)**\n\n---\n\nTo your clearest path forward,\n\n[Signature]\n\nP.S. Whichever quest you choose, it takes only 15 minutes for your first lesson. Tomorrow, I will explain why those 15 minutes might be the most important quarter-hour of your week."
},

'co-4': {
    subject: '15 minutes that could change your health',
    preheader: 'The people who transform are not different. They just pressed play.',
    img: 'https://storyblok-cdn.mindvalley.com/f/60579/1200x770/c5a3099305/10x_lp_signup_top_d.jpg',
    schwartz: 'Product-Aware', cialdini: 'Commitment/Consistency',
    cta: 'Open App \u2192', url: 'https://www.mindvalley.com/app',
    body: "I have watched hundreds of thousands of people join Mindvalley over the years.\n\nThe ones who transform their health and their lives are not more disciplined, more motivated, or more genetically gifted than the rest.\n\n**They did one thing differently: they did not wait for the perfect moment. They pressed play.**\n\n---\n\nYour first lesson takes about **15 minutes.**\n\nNot an hour. Not a weekend retreat. Not a 90-day bootcamp before you see results.\n\nFifteen minutes. While you drink your morning coffee. While you walk the dog. While you stretch on the living room floor.\n\n**That is 15 minutes to:**\n\n--> Begin rewiring how you approach your biggest health challenges\n--> Experience a world-class teacher guiding you step by step\n--> Feel the first subtle shift -- the one that tells you something is different\n\n---\n\n**Here is what most members report:**\n\nLesson 1: \"That was interesting.\"\nLesson 2: \"Okay, I see where this is going.\"\nLesson 3: **\"Wait -- why did no one tell me this before?\"**\n\nThe \"aha moment\" almost always lands within the first three lessons. But you have to start to feel it.\n\n---\n\n**The compound effect is real.**\n\n15 minutes a day for 21 days = 5.25 hours of focused health education from a world-class expert. That is more actionable longevity knowledge than most people absorb in a lifetime of random Google searches.\n\nAnd unlike random advice, what you learn here is sequenced. Each lesson builds on the last. Each day compounds.\n\n---\n\nOpen the app. Press play. Your first lesson is waiting.\n\n**[Open App \u2192](https://www.mindvalley.com/app)**\n\n---\n\nRooting for you,\n\n[Signature]\n\nP.S. In two days, I will share the full 4-quest longevity roadmap for your collection -- the exact sequence our healthiest members follow. But first, get that first lesson done. Everything builds from here."
},

'co-5': {
    subject: 'The 4-quest longevity roadmap (your collection blueprint)',
    preheader: 'A 4-month health transformation. Here is the exact sequence.',
    img: 'https://storyblok-cdn.mindvalley.com/f/60579/1200x770/c5a3099305/10x_lp_signup_top_d.jpg',
    schwartz: 'Product-Aware', cialdini: 'Authority',
    cta: 'Start Full Quest \u2192', url: 'https://www.mindvalley.com/longevity-collection',
    body: "Most people approach health like a buffet -- a little of this, a little of that, no real sequence.\n\nThat is why most health improvement does not stick.\n\n**What I am about to share is different.** This is the exact learning path our highest-performing longevity members follow. It is designed as a system -- each quest builds on the last.\n\n---\n\n**THE 4-QUEST LONGEVITY ROADMAP**\n\n**Quest 1 -- Weeks 1-3: 10x Fitness (Lorenzo Delano)**\n--> Build the body. 15-minute micro-workouts that build lean muscle, boost metabolism, and increase VO2 max -- the single strongest predictor of lifespan.\n--> **Result:** You are stronger, leaner, and more energetic. Your body starts looking and feeling younger.\n\n**Quest 2 -- Weeks 4-7: WildFit (Eric Edmeades)**\n--> Fix the fuel. Reprogram your relationship with food at the psychological level. No diets. No willpower. Just a permanent shift in how you eat.\n--> **Result:** Cravings dissolve. Weight normalizes. Energy stabilizes. Inflammation drops.\n\n**Quest 3 -- Weeks 8-10: The Mastery of Sleep (Dr. Michael Breus)**\n--> Optimize recovery. Discover your chronotype. Restructure your sleep for maximum deep sleep and REM.\n--> **Result:** You wake up feeling restored. Cognitive performance sharpens. Growth hormone production optimizes.\n\n**Quest 4 -- Weeks 11-14: Beyond Fasting (Ronan Oliveira)**\n--> Complete the system. Master intermittent fasting for metabolic efficiency, longevity, and peak mental clarity. Learn your personal fasting sweet spot.\n--> **Result:** Metabolic efficiency unlocked. Cellular repair activated. Weight management becomes effortless.\n\n---\n\n**After the Core 4 -- Months 4-6:**\n\nExplore the 24 bonus programs. Breathwork. Stress management. Meditation. Flexibility. Hormonal health. Peak athletic performance.\n\nThink of the first 14 weeks as building the foundation. Months 4-6 are building the house.\n\n---\n\n**This is a 6-month biological reset.**\n\nNot a 30-day challenge that fades. Not a crash diet that rebounds. A systematic reconstruction of how your body moves, fuels, recovers, and ages.\n\nStart Quest 1 today.\n\n**[Start Full Quest \u2192](https://www.mindvalley.com/longevity-collection)**\n\n---\n\nTo your complete transformation,\n\n[Signature]\n\nP.S. Bookmark this email. Seriously. You will want to come back to this roadmap as you progress through each quest. In two days, I will check in on your Week 1 progress."
},

'co-6': {
    subject: "Week 1 done -- what's shifting in your body?",
    preheader: 'Something is already different. Here is what other members experience.',
    img: 'https://storyblok-cdn.mindvalley.com/f/60579/1200x770/c5a3099305/10x_lp_signup_top_d.jpg',
    schwartz: 'Product-Aware', cialdini: 'Social Proof',
    cta: 'Continue Quest \u2192', url: 'https://www.mindvalley.com/longevity-collection',
    body: "One week.\n\nSeven days since you stepped into the Longevity Collection. Whether you have completed seven lessons or you are just finding your rhythm -- **something has already shifted.**\n\nThe simple act of committing to daily health education changes how your body responds. You are already different from the version of you seven days ago.\n\n---\n\n**What Other Members Typically Experience by Week 1:**\n\n--> **Better morning energy.** Even before changing your routine drastically, the awareness alone shifts behavior. You start making slightly better choices -- and your body notices immediately.\n--> **Improved sleep onset.** If you started Mastery of Sleep, Dr. Breus's chronotype insights often produce results on the very first night. Members report falling asleep 15-20 minutes faster.\n--> **First workout completed.** If you started 10x Fitness, you have felt what a scientifically optimized 15-minute workout can do. Your muscles are waking up.\n--> **New awareness of food patterns.** If you started WildFit, Eric's psychological reframes are already running in the background. You are noticing things about your eating that you never noticed before.\n--> **Fasting clarity.** If you started Beyond Fasting, Ronan's personalized fasting window is already shifting your energy patterns. Many members report sharper thinking during their fast.\n\nThese are not extraordinary results. **These are typical Week 1 outcomes.** The extraordinary results come after Week 2.\n\n---\n\n**Why Week 2 Matters More Than Week 1:**\n\nNeuroscience and exercise physiology agree: new patterns begin to solidify after 7-14 days of consistent practice. What felt like effort in Week 1 starts becoming automatic in Week 2.\n\nThis is where the compound effect kicks in.\n\nA habit that takes willpower today becomes effortless by Day 14. And an effortless habit practiced for 21 days becomes part of who you are.\n\n---\n\n**So keep going.**\n\n15 minutes today. That is all. Not a heroic effort -- just consistency.\n\nThe members who see the biggest health transformations are not the most athletic. They are the most consistent. One lesson a day. Every day. That is the entire formula.\n\n**[Continue Quest \u2192](https://www.mindvalley.com/longevity-collection)**\n\n---\n\nProud of you for being here,\n\n[Signature]\n\nP.S. In three days, I will introduce you to some hidden gems inside your collection that most members do not discover until month 2. These bonus programs are not filler -- they are full-scale health tools worth hundreds each."
},

'co-7': {
    subject: 'Unlock the biohacking toolkit inside your collection',
    preheader: 'Beyond the core 4 -- these bonus programs are worth $199-$599 each.',
    img: 'https://storyblok-cdn.mindvalley.com/f/60579/1200x770/c5a3099305/10x_lp_signup_top_d.jpg',
    schwartz: 'Product-Aware', cialdini: 'Reciprocity',
    cta: 'Explore Tools \u2192', url: 'https://www.mindvalley.com/longevity-collection',
    body: "Quick question: **have you explored the 24 bonus programs yet?**\n\nMost members spend the first week or two focused on their core quest -- which is exactly right. But there is a library sitting inside your collection that most people do not discover until later.\n\nI do not want you to be one of those people. Because some of these programs are game-changers on their own.\n\n---\n\n**3 Bonus Programs Every Longevity-Focused Person Should Know About:**\n\n**1. The Longevity Blueprint** (Ben Greenfield)\n--> Ben is a former competitive bodybuilder, Ironman triathlete, and one of the top 100 most influential people in health and fitness. His program covers the 5 pillars of longevity -- from cold exposure to nutrition timing to environmental optimization. It is the complete big-picture map of how aging works at the cellular level.\n--> **Individual value: $399.** Included in your collection.\n\n**2. HyperBody** (Ronan Diego)\n--> Ronan is a peak performance coach who has trained Olympic athletes and Special Forces operators. HyperBody is a mobility and recovery system that keeps your joints, fascia, and connective tissue functioning decades younger than your calendar age.\n--> **Individual value: $299.** Included in your collection.\n\n**3. The Breathwork Blueprint** (Niraj Naik)\n--> Niraj reversed a chronic illness doctors said was incurable -- using only breathwork. This program teaches you proven breathing protocols for stress reduction, energy amplification, and cellular oxygenation.\n--> **Individual value: $199.** Included in your collection.\n\n---\n\n**These are not filler programs.** They are full-scale courses from practitioners who have spent decades in the health and longevity space.\n\nThe combined individual value of these three alone is nearly $900. You have them all.\n\n---\n\n**How to use them:**\n\nDo not interrupt your current quest. Finish your core program first.\n\nBut open the collection and browse. Bookmark the ones that speak to your current health challenges. When you finish your first quest, you will know exactly where to go next.\n\n**[Explore Tools \u2192](https://www.mindvalley.com/longevity-collection)**\n\n---\n\nTo your expanding health toolkit,\n\n[Signature]\n\nP.S. In four days, I will share stories from three members who used this collection to produce specific, measurable health results. Biological age reversals. Weight loss. Sleep improvements. Real data from real people."
},

'co-8': {
    subject: 'What 3 members did with this collection (health results inside)',
    preheader: 'Fasting clarity, weight lost, sleep fixed -- real stories.',
    img: 'https://storyblok-cdn.mindvalley.com/f/60579/1200x770/c5a3099305/10x_lp_signup_top_d.jpg',
    schwartz: 'Product-Aware', cialdini: 'Social Proof',
    cta: 'Explore Collection \u2192', url: 'https://www.mindvalley.com/longevity-collection',
    body: "I want to share something today -- not from me, but from three members who are working through the same collection you have.\n\nThese are not motivational stories. These are specific, measurable health results.\n\n---\n\n**DAVID, 54, AUSTIN** -- Tech executive, desk-bound 12 hours a day.\n\nStarted with 10x Fitness. Lorenzo's 15-minute workouts fit perfectly into his schedule. He gained 8 pounds of lean muscle in 3 months without a single gym session lasting longer than 20 minutes.\n\nThen Beyond Fasting. Ronan's personalized fasting protocol helped him find his sweet spot -- a 14-hour fast that maximized fat burning without affecting his energy.\n\n**6-month result: Lost 18 pounds. VO2 max improved by 22%. Says he has \"more energy at 54 than I had at 35.\" His wife noticed the change within the first month.**\n\n---\n\n**MARIA, 41, LONDON** -- Freelance designer, lifelong yo-yo dieter.\n\nStarted with WildFit. Eric Edmeades's psychological approach was the first thing that made her stop thinking about food all day. The cravings she had fought for 20 years dissolved within the first three weeks.\n\nThen Mastery of Sleep. She had been averaging 5 hours of broken sleep for years. Dr. Breus's chronotype system revealed she was a \"Dolphin\" -- and the sleep schedule she had been forcing was exactly wrong for her biology.\n\n**6-month result: Lost 32 pounds (and kept it off -- no rebound). Sleep went from 5 broken hours to 7.5 solid hours. Cortisol levels normalized. Her doctor took her off blood pressure medication.**\n\n---\n\n**JAMES, 38, SINGAPORE** -- Entrepreneur, chronic stress and fatigue.\n\nStarted with Beyond Fasting. Ronan's approach revealed that his fatigue was partly metabolic -- his eating patterns were spiking and crashing his blood sugar all day. The fasting protocol stabilized his energy within a week.\n\nThen 10x Fitness for the physical transformation, followed by Mastery of Sleep to fix his erratic rest schedule.\n\n**6-month result: Eliminated chronic fatigue. Built visible muscle definition for the first time in his life. Sleep improved from 5.5 to 7.5 hours. Says the collection was \"the best health investment I have ever made, and I have tried everything.\"**\n\n---\n\nThree different starting points. Three different health challenges. Same collection. Same 15 minutes a day.\n\nYou are on the same path they walked. Keep going.\n\n**[Explore Collection \u2192](https://www.mindvalley.com/longevity-collection)**\n\n---\n\nTo your story being written right now,\n\n[Signature]\n\nP.S. In one week, we hit the 3-week milestone. I will have something special for you then -- a checkpoint that will help you see exactly how far you have come and where the next health breakthrough lives."
},

'co-9': {
    subject: "21 days in -- here's what most members do next",
    preheader: '3-week milestone. Here is what you have built and what is ahead.',
    img: 'https://storyblok-cdn.mindvalley.com/f/60579/1200x770/c5a3099305/10x_lp_signup_top_d.jpg',
    schwartz: 'Most-Aware', cialdini: 'Commitment/Consistency',
    cta: 'Continue Journey \u2192', url: 'https://www.mindvalley.com/longevity-collection',
    body: "Three weeks ago, you made a decision that most people never make.\n\nNot just to buy a program -- but to systematically upgrade how your body moves, fuels, recovers, and ages. To treat health optimization as a life strategy, not a New Year's resolution.\n\n**Let me acknowledge that.**\n\n---\n\n**What You Have Built in 21 Days:**\n\n--> A daily health learning habit that is becoming automatic\n--> New frameworks running in the background of every decision you make about food, movement, and recovery\n--> At least one quest completed or well underway\n--> Tangible results -- better energy, improved sleep, less inflammation, or a fundamentally different relationship with food\n\nWhether you have been consistent every single day or you have had some gaps -- **you are in a fundamentally different place than you were 21 days ago.** The neural pathways are forming. The biological shifts are compounding.\n\n---\n\n**What Most Members Do at This Point:**\n\nIf you have completed your first quest -- congratulations. You are ahead of 80% of people who buy online health programs.\n\nHere is what the highest-performing members do next:\n\n--> **Start Quest 2.** Look at the 4-Quest Roadmap from my Day 5 email. Which quest is next? Begin that quest this week.\n--> **Layer in bonus programs.** Browse the 24 extras. Find one that addresses your most pressing health challenge right now.\n--> **Keep the streak alive.** The difference between people who transform and people who relapse is simple: they kept going past Day 21.\n\n---\n\n**Your Full Roadmap (reminder):**\n\n--> Weeks 1-3: 10x Fitness (build the body)\n--> Weeks 4-7: WildFit (fix the fuel)\n--> Weeks 8-10: Mastery of Sleep (optimize recovery)\n--> Weeks 11-14: Beyond Fasting (master metabolism)\n--> Months 4-6: 24 bonus programs (build the house)\n\nYou are 3 weeks in. The foundation is laid. Now the real building begins.\n\n---\n\nI want to share one more thing.\n\nMany members at this point start noticing something: their health transformation does not want to stay in one lane. You came for longevity. But now you are curious about meditation, relationships, productivity, spiritual growth, career optimization.\n\nThat is not a distraction. **That is a signal.**\n\nThe people who build truly extraordinary lives do not just optimize their bodies. They optimize themselves -- across every dimension.\n\nKeep that thought in mind. I will have more to share on this soon.\n\n**[Continue Journey \u2192](https://www.mindvalley.com/longevity-collection)**\n\n---\n\nWith deep respect for how far you have come,\n\n[Signature]\n\nP.S. You started with 28 programs. But what if you had access to 100+? Programs on mindset, relationships, career, speaking, leadership, and more? Many members at your stage start exploring that possibility. Stay tuned."
}

});
